andela/ah-orcas

.gitignore
authors/apps/authentication/backends.py
authors/apps/authentication/urls.py
authors/urls.py
requirements.txt

**What does this PR do?**
Upgrade Authors Haven app from Django 1.10 to Django 2.1
**Description of Task to be completed?**
- Upgrade Django app from version 1.10 to version 2.1
- Edit the urls in the urls.py files to accommodate the changes that came with the upgrade
**How should this be manually tested?**
- Clone the repo  : git clone https://github.com/andela/ah-orcas.git
- cd into ah-orcas directory
- Run django --version
**Any background context you want to provide?**
- Upgrading an app is important because new versions come with security upgrades hence ensures app security
- Upgrading the app helps in optimising performance since new versions come with new features that promote efficiency
**What are the relevant pivotal tracker stories?** …

#161254647 Upgrade the app from Django 1.10 to Django 2.1

---

.travis.yml
README.md

* This PR integrates Travis CI badge with README badge.
* Add Travis badge to the README file
* Create a .travis.yml file in the project folder
* Open the repo : git clone https://github.com/andela/ah-orcas.git
* switch to integrate-Travis branch
* Check the README file
* Travis makes working in a team for a software project easier with automated builds which  are triggered automatically when each developer checks in their code to the repository.
* It also helps  to automatically run tests and other preliminary build steps
[#161254651](https://www.pivotaltracker.com/story/show/161254651)

#161254651 Integrate Travis CI with README badge

---

authors/settings.py
requirements.txt

* This Configure Authors Haven to use PostgreSQL as DB Engine.
* Set environment variables to be used in database
* Change Database engine from SQLite to PostgreSQL
* add psycopg2 to dependencies variables - requirements.txt
* Open the repo : ```git clone https://github.com/andela/ah-orcas.git```
* ```cd ah-orcas```
* ```git checkout ch-configure-database-postgresql-161254652```
* ```python manage.py makemigrations authentication```
* ```python manage.py migrate authentication```
* PostgreSQL is a powerful, open source object-relational database system with over 30 years of active development that has earned it a strong reputation for reliability, feature robustness, and performance.
[#161254652](https://www.pivotaltracker.com/story/show/161254652)

#161254652 Configure Authors Haven to use PostgreSQL as DB Engine 

---

.github/pull_request_template.md

- This is the sample format for adding details to a pull request.
- Create a sample format file for creating pull requests.
- N/A
- This is just a template that should bring uniformity to our pull request descriptions.
[#161411024](https://www.pivotaltracker.com/story/show/161411024)
- Are you content with the layout? 
- If not, what do you suggest should be changed or improved on?

#161411024 Pull Request format 

---

README.md

```This PR Integrates code climate with with Github for the purpose of displaying the measure of code quality on the README.md  ```
```
Add markdown link for the badge on README.md
```
```
On the README.md on Github, code climate badge should be displayed.
```
```
Your code quality is displayed in form of A,B,C,D... whereby high quality means an A
The Grading is only visible on Github not the on the editor
```
[#161444013](https://www.pivotaltracker.com/story/show/161444013)
- None

#161444013 Integrate code climate with Github

---

README.md

What does this PR do?
This PR integrates codacy and add badge to README
Description of Task to be completed?
Add codacy badge to README
How should this be manually tested?
Check that the README contains a valid codacy badge
Any background context you want to provide?
Codacy automates code reviews and monitors code quality over time. Static analysis, code coverage and metrics for Python.
What are the relevant pivotal tracker stories?
[#161472787](https://www.pivotaltracker.com/story/show/161472787)

#161472787 integrate codacy

---

.travis.yml
README.md

* This PR integrates coveralls badge with the README file.
* Add coveralls badge to the README file
* Add a command for installing coveralls in the .travis.yml file 
* Check that the the readme file contains a valid coveralls badge
Coveralls helps in tracking the app's code coverage over time, and ensures that all the new code is fully covered.
[#161254654](https://www.pivotaltracker.com/story/show/161254654)

#161254654 Integrate Coveralls badge with README file

---

.hound.yml

This PR integrate hound with github
Make sure eslint config and hound are configured to check for style violations
Hound should comment on pull request
- Hound watches for pull requests on all active repos
- Hound will review all GitHub pull requests that are opened on an activated repo for violations of your style guide
- Hound uses Flake8
[#161254607](https://www.pivotaltracker.com/story/show/161254607)

#161254607 integrate hound with github

---

Procfile

What does this PR do?
Adds Procfile for heroku
Description of Task to be completed?
Adds Procfile with db migrations commands for heroku
How should this be manually tested?
Manually deploy the branch on heroku and check the logs
Any background context you want to provide?
Database migrations should be automatically run whenever there are changes
What are the relevant pivotal tracker stories?
[#161254653](https://www.pivotaltracker.com/story/show/161254653)

 #161254653 add db migrations to heroku

---

authors/apps/authentication/backends.py
authors/apps/authentication/models.py
authors/apps/authentication/renderers.py
authors/apps/authentication/serializers.py
authors/apps/authentication/tests/test_user.py
authors/apps/authentication/urls.py

This PR merges implementation of JWT based authentication feature branch with the develop branch
Implement JWT authentication token that is sent to users upon registration/login
Users are able to use the token whenever they make calls to all endpoints
After cloning the repo, cd into it and RUN `python3 manage.py runserver`
- Using Postman, test the registration endpoint and check whether the authentication token is returned
- When a user successfully registers/logs in using their credentials, JWT is generated and saved in local storage. 
- Whenever the user wants to access other endpoints, the token is sent in the header of the request. 
- The server then checks for a valid JWT in the Authorisation header, and if found, the user will be allowed access.
- This minimises the number of …

#161254656 Implement JWT authentication

---

.coveragerc
.travis.yml
requirements.txt

`This PR sets up the testing environment on TravisCI`
`Have the test environment setup and testing for the required files`
`Open TravisCI and check the coverage report in the ah-orcas repository.`
`Coveralls helps in tracking the app's code coverage over time, and ensures that all the new code is fully covered.`
[#161254654](https://www.pivotaltracker.com/story/show/161254654)

#161254654 Setup Test Environment on TravisCI 

---

authors/apps/authentication/models.py
authors/apps/authentication/serializers.py
authors/apps/authentication/tests/test_user.py

Users should receive descriptive signup/Registration validation errors
Users should receive a descriptive error message when they enter invalid user parameters in an attempt to signup.
Invalid user parameters includes:
- existing user email
- invalid email
- password of length less than 8
- password not being alphanumeric
Use postman to sign up with invalid user parameters
An attempt to sign up with invalid characters should return an error with a descriptive message. 
[#161254657](https://www.pivotaltracker.com/story/show/161254657)

#161254657 descriptive validation errors

---

authors/apps/authentication/serializers.py
authors/apps/authentication/urls.py
authors/apps/authentication/views.py
authors/settings.py
requirements.txt
sample.env

- Add swagger documentation 
- Setup documentation for the endpoints. 
- clone the project
```
- git clone https://github.com/andela/ah-orcas
```
- setup your .env file. See sample.env file and run it
```
source .env
```
- run the app
```code
python manage.py runserver
```
- open your browser
```
http://127.0.0.1:8000/api/
```
- I have also added a sample env file to make cloning easier and more efficient.
- The documentation is setup will automatically update other endpoints as they are being created.
- [161254655](https://www.pivotaltracker.com/story/show/161254655)

#161254655 Django Rest Framework Swagger Documentation

---

.gitignore
authors/apps/authentication/backends.py
authors/apps/authentication/serializers.py
authors/apps/authentication/templates/activate_account.html
authors/apps/authentication/templates/alert_reset_password.html
authors/apps/authentication/tests/test_email_verification.py
authors/apps/authentication/urls.py
authors/apps/authentication/views.py
authors/apps/core/exceptions.py
authors/settings.py
requirements.txt

- send token link to the registered user email.
- reset password for users.
- Password reset functionality is missing in our application. Its invaluable in instances where our users forget their login credentials.
``` 
```
- Navigate to this branch.
``` 
$ git clone git checkout  ft-reset-password-161254660
```
- create a python virtual environment in your local machine and start it.
```code
$ virtualenv env
$ source env/bin/activate
```
```
$ source .env
```
- Run the app
```
```
- Test the endpoint.
```
api/users/forget/
api/users/rest/<str:hashed_email/<str:token>
```
- I used django PasswordResetTokenGenerator …

#161254660 Implement password reset

---

.travis.yml
authors/apps/articles/apps.py
authors/apps/articles/models.py
authors/apps/articles/serializers.py
authors/apps/articles/tests/templates/activate_account.html
authors/apps/articles/tests/test_rate_article.py
authors/apps/articles/urls.py
authors/apps/articles/views.py
authors/apps/authentication/tests/test_email_verification.py
authors/apps/authentication/urls.py
authors/apps/authentication/views.py
authors/settings.py
authors/urls.py
requirements.txt

```registered user can rate an article and view article rates```
```Our community as authors is built on trust. Rating each other's articles helps to gain and build trust. Leaving a rating is your chance to give other authors a general idea of what we feel about their content. ```
``` 
```
- Navigate to this branch.
``` 
$ git clone git checkout  ft-reset-password-161254660
```
- create a python virtual environment in your local machine and start it.
```code
$ virtualenv env
$ source env/bin/activate
```
```
$ source .env
```
- Run the app
```
```
- Test the endpoint.
```
api/users/article/<str:slug>/ …
```

#161254664 Rate an article

---

authors/apps/article/likes_dislike_views.py
authors/apps/article/models.py
authors/apps/article/tests/base_like_test.py
authors/apps/article/tests/templates/activate_account.html
authors/apps/article/tests/test_dislike_an_article.py
authors/apps/article/tests/test_like_an_article.py
authors/apps/article/tests/test_rate_article.py
authors/apps/article/urls.py
authors/apps/article/views.py

```Like and dislike an article```
```This PR makes users to appreciate those authors who created good articles by liking the article it also makes user to encourage those who didn't meet the expectation by disliking ```
``` 
```
- Navigate to this branch.
``` 
$ git clone git checkout  ft-like-dislike-article-161254667
```
- create a python virtual environment in your local machine and start it.
```code
$ virtualenv env
$ source env/bin/activate
```
```
$ source .env
```
- Run the app
```
```
- Test the endpoint.
```
api/users/article/dislike/<str:slug>/
api/users/article/like/<str:pk>/
``` …

#161254667 Like and dislike  an article

---

.travis.yml
authors/apps/report/models.py
authors/apps/report/serializers.py
authors/apps/report/test/test_report.py
authors/apps/report/urls.py
authors/apps/report/views.py
authors/settings.py
authors/urls.py

- User can report an article.
- As an authenticated user i should be able to report articles that violate terms of agreement or are plagiarised to the authors haven admin for removal and or any other actions as per the terms of engagement.
- git clone this repo
```
$ git clone https://github.com/andela/ah-orcas
```
- Navigate to this branch
```
$git checkout ft-report-article-161254680
```
- Setup the environments, see sample.env. Then install them.
```
- source .env
```
- Install the requirements.txt
```
pip install -r requirements.txt
```
- run the endpoint.
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/380577a3770b04002007)
- To report an article, one has to input their name as the reporter, title of the article then on the body they …

#161254680 report article

---

authors/apps/article/likes_dislike_views.py
authors/apps/article/models.py
authors/apps/article/renderers.py
authors/apps/article/serializers.py
authors/apps/article/tests/test_favorite.py
authors/apps/article/urls.py
authors/settings.py

```Adds functionality for users to favorite or unfavorite an article  ```
```
an authenticated user hitting api/articles/<slug>/favorite/
with POST request should be able to favorite an article
with DELETE request should be able to unfavorite an article
```
$ virtualenv env
$ source env/bin/activate
$ cd env
```
``` 
```
- Switch to this branch
``` 
$  git checkout  ft-favorite-article-161254669
```
```
$ source .env
```
- Run the app
```
```Authentication is required```
[#161254669](https://www.pivotaltracker.com/story/show/161254669)

#161254669 implement favoriting articles

---

authors/apps/article/models.py
authors/apps/article/tests/test_search.py
authors/apps/article/tests/test_tag_article.py
authors/apps/article/urls.py
authors/apps/article/views.py

This PR allows users to add tags to articles
A user should be able to add tags to articles that they create
``` 
```
- Switch to this branch
``` 
$  git checkout  ft-article-comments-161254665
```
```
$ source .env
```
- Run the app
```
```
- Create an article using Postman: http://localhost:8000/api/article/create/
- Test the endpoint using Postman:
endpoint: http://localhost:8000/api/article/tag/article-slug
body: 
```
{
"article":{
"tags":[
"train",
"dragon"
]
}
}
```
Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. 
Tagging allows …

#161254673 tag articles

---

authors/apps/article/views.py

This PR allows you to use tag articles in Swagger
A user should be able to use tag Article from Swagger UI. It currently does not work because
the ArticleTag class does not have serializer_class defined.
``` 
```
- Switch to this branch
``` 
$  git checkout  ft-article-comments-161254665
```
```
$ source .env
```
- Run the app
```
```
- Login: http://localhost:8000/api/users/login/ to get a token
- Go to: http://localhost:8000/api/ and click `Authorize` on the top left
- In the text box provided, add `Bearer your-token` and submit
- A list of Authorized endpoints should appear. Find `PUT /api/article/tag/{slug} ` and …

#161254673 add tag to articles
